== Einzelne Artikel anzeigen

Bisher werden immer alle Artikel des Blogs auf einmal angezeigt.
Um später aber Kommentare zu einzelnen Artikeln anzeigen zu können,
sollten auch einzelne Artikel angezeigt werden können.


Damit das möglich ist, muss:

* Der `BlogService` entsprechend anpassen,
sodass einzelne Artikel abgefragt werden können.
* Der Controller muss auf entsprechende Seitenaufrufe reagieren können
* Die `SecurityCofig` muss diese Aufrufe zulassen
* Eine passende View muss hinzugefügt werden

=== BlogService anpassen

Dem Interface fügen wir eine Methode zum Abfragen
eines einzelnen Artikels anhand seiner ID hinzu:

[source,java]
.BlogService.java
----
include::../javasrc/11/src/main/java/tdpe/example/domain/BlogService.java[tags=class]
----


Diese Methode implementieren wir dann entsprechend:
[source,java]
.BlogServiceImpl.java
----
include::../javasrc/11/src/main/java/tdpe/example/domain/BlogServiceImpl.java[tags=class]
----

<1> `Article` haben als ID einen `Long`, den übergebenen String müssen wir also parsen

<2> Mit der ID fragen wir dann den Artikel ab

<3> Wird einer gefunden, geben wir diesen zurück, ansonsten werfen wir eine Exception

=== Controller anpassen

[source,java]
.BlogController.java
----
include::../javasrc/11/src/main/java/tdpe/example/web/BlogController.java[tags=single_article]
----

<1> Der Pfad, auf den die Methode reagieren soll, sieht auf den ersten Blick erst mal komisch auf.
Der Teil innerhalb der geschweiften Klammern nennt sich Path-Variable und ist im wesentlichen
genau das - ein variabler Teil innerhalb des Pfades.
Dieser bekommt einen Namen, `id`, und in diesem Fall zusätzlich einen regulären Audruck,
der valide Belegungen angibt, in diesem Fall `\d+`, also mindestens eine Ziffer.
Die Methode reagiert damit auf Pfade wie z.B. `/articles/0` und `/articles/123`,
aber nicht auf `/articles/a` oder `/articles/0a`

<2> Die `PathVariable` können wir dann als Methoden-Parameter angeben.
Dazu muss diese mit `@PathVariable` annotiert sein, der passende Name muss angegeben sein
und sie muss einen passenden Typ haben.

<3> Als View geben wir "article/article" an, dieses referenziert damit auf `src/main/resources/templates/article/article.html`,
welche wir gleich noch anlegen

<4> Dann laden wir über den Service den entsprechenden Artikel und übergeben diesen dem Model

=== Security-Config anpassen

Bisher dürfen nicht-angemeldete Nutzer nur auf `/` zugreifen, der Zugriff auf
Artikel sollte aber natürlich auch möglich sein.

Dazu müssen wir den Pfad der Security-Config hinzufügen:

[source,java]
.SecurityConfig.java
----
include::../javasrc/11/src/main/java/tdpe/example/SecurityConfig.java[tags=configure]
----

<1> Wir geben dazu einfach den Pfad, auf den der Controller reagiert,
als weiteren Pfad an, auf den alle zugreifen dürften

=== View erstellen

Als View für einzelne Artikel erstellen wir die `article.html`
in `src/main/resource/templates/article`:


[source, html]
.article.html
----
include::../javasrc/11/src/main/resources/templates/article/article.html[]
----

<1> Wir lassen die Title und Text des Artikels wie auch auf der Hauptseite ausgeben

<2> Außerdem zeige wir den Zeitpunkt des Artikels an.
Dazu nutzen wir das `#temporals`-Objekt,
welches von Thymeleaf zum Formatieren von Daten angeboten wird.
Darauf rufen wir die `format`-Methode auf, die ein Datum lesbar formatiert,
und übergeben den Veröffentlichungszeitpunkt des Artikels


Was noch fehlt, ist ein Link zu den einzelnen Artikeln.
Diesen fügen wir in blog.html hinzu:


[source, html]
.blog.html
----
include::../javasrc/11/src/main/resources/templates/blog.html[tags=articles]
----

<1> Die Überschrift umschließen wir dazu mit einem Anker, welcher als Ziel die Seite eines einzelnen Artikels hat.
Für die URL nutzen wir die Thymeleaf-URL-Syntax.
Für diese geben wir den Link mit Platzhaltern an (`articles/{article_id}`) und
legen danach fest, wie diese gefüllt werden sollen (`article_id=${article.id}`)


=== Starten

Wenn wir starten, sehen wir auf der Hauptseite Links zu den einzelnen Artikeln.

Öffnen wir damit einen, sehen wir den einzelnen Artikel zusammen mit dem Zeitpunkt.
