== Code verstehen
:experimental:
:icons: font
:imagesdir: img
:source-highlighter: highlightjs

=== StartUp

[source,java]
.ExampleApplication.java
----
include::../javasrc/1/src/main/java/tdpe/example/ExampleApplication.java[tags=class]
----

<1> Gibt an, dass dieses Projekt eine Spring-Boot-Application ist.
 Dies aktiviert u.a. Auto-Configuration (Jede im Projekt gefundene Konfiguration wird angewandt)
 und Component-Scan (Alle im Projekt gefundenen Services werden als Beans bereitgestellt)

<2> Zusätzlich wird in der `main` die Klasse an Spring zum Starten übergeben, ähnlich, wie z.B. mit JavaFX

=== Controller

[source,java]
.WelcomeController.java
----
include::../javasrc/1/src/main/java/tdpe/example/WelcomeController.java[tags=class]
----

<1> Diese Klasse ist durch die Annotation ein Controller.
Controller in einer Spring WebMVC-Anwendung nehmen HTTP-Anfragen entgegen, erzeugen ein geeignetes Model und benennen die zu verwendende View.
Sie bieten den Startpunkt, von dem aus Aktionen des Benutzers verarbeitet werden

<2> Das `@RequestMapping("/")` deutet an, dass diese Methode aufgerufen werden soll wenn eine HTTP-Anfrage auf den Pfad `"/"` stattfindet.
Die Methode gibt ein ModelAndView zurück, die für die Antwort an den Browser dargestellt werden soll.
ModelAndView enthält den Namen einer View und die dazugehörigen Daten.
Der Name der View, hier `welcome`, wird aufgelöst zu einem Html-Template, src/main/resources/templates/welcome.html.
Das Model besteht dabei aus mehreren Objekten, die in der View über ihren Namen referenzierbar sind

<3> Mit dieser Annotation wird Spring angewiesen,
diese Variable mit einem Wert aus der Datei `application.properties` vorzubelegen, der unter dem Schlüssel `application.message` zu finden ist.
Durch das hinzufügen von `":Hello World"` in der Annotation wird `"Hello World"` als Standardbelegung angenommen, falls der gesuchte Schlüssel in den `application.properties` nicht gefunden wurde.
Würde die Standardbelegung im `@Value` weggelassen, gäbe es statt dessen beim Anwendungsstart eine Exception wenn die entsprechende Property fehlt


=== Konfigurationen



[source,properties]
.application.properties
----
include::../javasrc/1/src/main/resources/application.properties[]
----

Diese Zeile liefert die Belegung für das per `@Value` befüllte Feld von `WelcomeController`.

=== View

Im Kern handelt es sich bei der Datei um eine HTML-Datei, mit einigen Erweiterungen.
Dementsprechend hat sie die übliche Struktur eines HTML Dokuments mit einem HTML5 Doctype.
Ein Vorteil von Thymeleaf ist an dieser Stelle, dass diese Datei auch ohne das Auflösen von Variablen oder Tags im Browser anzeigbar ist.

Dieses Template zeigt vor allem, wie man auf Variablen zugreift, die entweder im Controller ins Model eingefügt worden sind, oder innerhalb der Template definiert wurden:


[source, html]
.welcome.html
----

include::../javasrc/1/src/main/resources/templates/welcome.html[]
----

<1> Alle mit `th` beginnenden Attribute werden während des Renderns von Thymeleaf ausgewertet. Die Dollar-Notation dient dabei dem Zugreifen auf Variablen. Mit `${message}` greift man z.B. auf den im Model hinterlegten String zu.

<2> Handelt es sich bei der Variablen nicht um einen String wie bei `time`, wird sie zur Ausgabe mittels ihrer `toString()`-Methode formatiert.

=== Tests

TODO

=== Zusammenfassung

* Die Anwendung verwendet generell die Standardeinstellungen die von Spring Boot vorgeschlagen werden
* Bei Anfragen auf dem Pfad / wird die Datei `welcome.html` mit einem Datum und einer Nachricht versorgt und gerendert
* Konfigurationsdaten liegen in `application.properties`
* Als Templatesprache wird Thymeleaf verwendet.
Die Beispielseite zeigt, wie man einfachen Text ausgibt und Daten vom Java-Teil eurer Anwendung (das sogenannte Backend)
in den HTML-Teil eurer Anwendung (das sogenannte Frontend) transferiert.
