== Services

Die Artikel des Blogs sollten natürlich nicht einfach so im Controller der Anwenung erstellt werden.
Stattdessen sollte dieser die aus dem Model der Anwendung geladen werden, sodass man z.B. später eine Datenbank anbinden kann.

=== Service-Interface

Der Controller braucht also einen Service, der die Artikel bereitstellt.

Dazu definieren wir als erstes ein passendes Interface:

[source,java]
.ArticleService.java
----
TODO:
public interface BlogService {
    List<Article> getArticles();
}
----

Der Service bekommt erstmal nur eine einzelne Methode - zum Laden aller Artikel.


=== Controller anpassen

Diesen benutzen wir dann im Controller, anstatt dort die Artikel neu zu erstellen:

[source,java]
.BlogController.java
----
TODO:
class BlogController {

    private BlogService blogService;

    @Autowired //<1>
    public BlogController(BlogService blogService) {
        this.blogService=blogService;
    }

    @RequestMapping("/")
    public ModelAndView showBlog() {
        var modelAndView = new ModelAndView("blog");

        var articles = blogService.getArticles(); //<2>
        modelAndView.addObject("articles", articles);

        return modelAndView;
    }
}
----

<1> Hier benutzen wir wieder `@Autowired` -
diese Annotation weißt Spring an, ein Objekt der Klasse `BlogService` zu übergeben,
wenn die Klasse instanziert wird.

<2> Den _injizierten_ `BlogService` benutzen wir dann, um eine Liste der Artikel zu erhalten.

=== Tests anpassen

Durch die Änderung des Konstruktors von `BlogController` kompiliert der Tests nicht mehr,
da wir in diesem den Default-Konstruktor benutzen.

Wir müssen also auch im Test eine Instanz von `BlogService` übergeben.

Anstatt dabei das Interface
