== Services

Die Artikel des Blogs sollten natürlich nicht einfach so im Controller der Anwenung erstellt werden.
Stattdessen sollte dieser die aus dem Model der Anwendung geladen werden, sodass man z.B. später eine Datenbank anbinden kann.

=== Service-Interface

Der Controller braucht also einen Service, der die Artikel bereitstellt.

Dazu definieren wir als erstes ein passendes Interface:

[source,java]
.BlogService.java
----
include::../javasrc/5/src/main/java/tdpe/example/domain/BlogService.java[tags=class]
----

Der Service bekommt erstmal nur eine einzelne Methode - zum Laden aller Artikel.


=== Controller anpassen

Diesen benutzen wir dann im Controller, anstatt dort die Artikel neu zu erstellen:

[source,java]
.BlogController.java
----
include::../javasrc/5/src/main/java/tdpe/example/web/BlogController.java[tags=class]
----

<1> Hier benutzen wir wieder `@Autowired` -
diese Annotation weißt Spring an, ein Objekt der Klasse `BlogService` zu übergeben,
wenn die Klasse instanziert wird.

<2> Den _injizierten_ `BlogService` benutzen wir dann, um eine Liste der Artikel zu erhalten.

=== Tests anpassen

Durch die Änderung des Konstruktors von `BlogController` kompiliert der Tests nicht mehr,
da wir in diesem den Default-Konstruktor benutzen.

Wir müssen also auch im Test eine Instanz von `BlogService` übergeben.

Dazu nutzen wir _Mocking_ - dabei erstellen wir keine echte Implementierung des Interfaces,
sondern lassen durch eine Library eine Implementierung erstellen, deren Verhalten wir dann im Nachhinein steuern können.


[source,java]
.BlogControllerTest.java
----
include::../javasrc/5/src/test/java/tdpe/example/web/BlogControllerTest.java[tags=test]
----

<1> Wir legen eine Instanzvariable des benötigen Interfaces an.
Dieses annotieren wir mit `@Mock`, wodurch die Library angewiesen wird, einen Mock dieses Interfaces bereitzustellen

<2> Vor jedem Test weisen wir die Library dann an, alle mit `@Mock` annotierten Felder zu inititalisieren.

<3> Im Test benutzen wir dann den initialisieren Mock.
