== Artikel anlegen

Angemeldete Nutzer sollen natürlich auch Artikel schreiben können.

Was wir dazu brauchen, sind im wesentlichen eine Eingabemaske (View), ein Controller,
der die Eingaben verarbeitet, und einen Service, der die neuen Artikel speichert.

=== Service

Zuerst passen wir den Service entsprechend an:

[source,java]
.BlogService.java
----
include::../javasrc/8/src/main/java/tdpe/example/domain/BlogService.java[tags=class]
----
<1> hinzugefügt wird eine Methode, die einen Artikel für den Nutzer mit gegebenem Text und Titel erstellt


Diese Methode implementieren wir dann entsprechend:
[source,java]
.BlogServiceImpl.java
----
include::../javasrc/8/src/main/java/tdpe/example/domain/BlogServiceImpl.java[tags=class]
----

<1> der neue Artikel wird erzeugt

<2> diesen speichern wir im Repository. Dabei bekommen wir einen Artikel zurück, welchen wir dann auch zurückgeben

=== Eingabemaske für neue Artikel

==== Controller

Im Controller brauchen wir als erstes eine Methode, die eine View zurück gibt,
in der man den neuen Artikel eingeben kann.

[source,java]
.BlogController.java
----
include::../javasrc/8/src/main/java/tdpe/example/web/BlogController.java[tags=show_form]
----

<1> Die View soll dabei bei Aufrufen von `/articles/add` zurückgegeben werden

<2> Die View heißt `add` und liegt im Ordner `article`

<3> Dem Model fügen wir ein neues `CreateArticleCmd` hinzu

==== Command-Objekt


`CreateArticleCmd` ist dabei ein Command-Objekt, welches dazu dient,
die eingegeben Daten an den Controller weiter zu geben.
Es enthält nur die für einen neuen Artikel nötigen Felder und Getter und Setter für diese:


[source,java]
.CreateArticleCmd.java
----
include::../javasrc/8/src/main/java/tdpe/example/web/CreateArticleCmd.java[tags=class]
----

==== View

Das Command-Objekt nutzen wir dann in der View.
Für diese legen wir in `src/main/resources/templates` einen neuen Ordner `article` und in diesem
die Datei `add.html` an:

[source, html]
.add.html
----
include::../javasrc/8/src/main/resources/templates/article/add.html[]
----

<1> Die Seite enthält eine einfache `form`
* als `th:action` ist `@{/articles/add}` angegeben - `th:action` löst thymeleaf
zu `action` auf und wertet dabei die angeben URL aus. Dies ist die URL,
zu der die ausgefüllte Form geschickt wird
* mit `th:object` verweisen wir auf das Model-Objekt, welches mit dieser Form
gefüllt werden soll. In diesem Fall das dem Model hinzugefügte `createArticleCmd`
* als Methode geben wir `post` an, damit der Browser beim abschicken des Formlars
einen POST statt GET-Request durchführt

<2> Die Form enthält zwei input-Felder. Diese referenzieren mit `th:field` und `*{}` jeweils
das zugehörige Feld aus dem hinterlegtem Model - `*{titel}` z.B. `createArticleCmd.title`


In der blog.html legen wir außerdem noch einen Link auf die neue Seite an:

[source, html]
.blog.html
----
include::../javasrc/8/src/main/resources/templates/blog.html[tag=link]
----

=== Artikel anlegen

Damit die gesendete Form auch zum Anlegen eines neuen Artikels führt, muss im
Controller noch eine entsprechende Methode angelegt werden:

[source,java]
.BlogController.java
----
include::../javasrc/8/src/main/java/tdpe/example/web/BlogController.java[tags=post_form]
----

<1> Statt einem `GetMapping` benutzen wir ein `PostMapping`,
damit auf POST-Request statt GET-Requests reagiert wird

<2> Übergeben beokmmt die Methode ein Objekt unserer Nutzer-Klasse. Dieses ist
mit `AuthenticationPrincipal` annotiert, sodass Spring dort den aktuell
angemeldeten Nutzer übergibt

<3> Außerdem wird ein `CreateArticleCmd` übergeben, welches auch in der Form referenziert wurde

<4> In der Methode benutzen wir die `addArticle`-Methode des BlogService, um einen
neuen Artikel zu erstellen

<5> Zurück geben wir ein neues ModelAndView-Objekt, welchem wir als View-namen `redirect:/` übergeben.
Durch das `redirect:` führt dies dazu, dass der Browser auf die `/`-Seite unserer Anwednung weiterleitet

=== Starten
