== Datenbank persistieren

Die Datenbank soll natürlich nicht bei jedem Start neu geladen werden,
sondern mehrere Neustarts überdauern.

Außerdem wird die Datenbank aktuell aus einem SQL-Skript mit initialen Daten befüllt.
Dafür muss man z.B. den genauen Aufbau der Datenbank kennen.
Schöner wäre es, wenn man dies über Java-Code lösen könnte.

=== Service anpassen

Aktuell kann der `UserService` nur Nutzer laden, aber keine anlegen.
Wir müssen also eine Methode zum Speichern der Nutzer hinzufügen:

[source, java]
.UserService.java
----
include::../javasrc/9/src/main/java/tdpe/example/domain/UserService.java[tags=class]
----

<1> Dem Interface fügen wir dazu eine einfache Methode zum erstellen der Nutzer hinzu

Außerdem braucht der Nutzer noch eine Möglichkeit, diesem Rollen hinzuzufügen:
[source, java]
.User.java
----
include::../javasrc/9/src/main/java/tdpe/example/domain/User.java[tags=addRole]
----

<1> Sollte der Nutzer noch keine Rollen haben, erstellen wir diese

<2> Den Rollen fügen wir dann die neue Rolle hinzu


[source, java]
.UserServiceImpl.java
----
include::../javasrc/9/src/main/java/tdpe/example/domain/UserServiceImpl.java[tags=createUser]
----

<1> Wir erstellen den neuen Nutzer mit den übergebenen Datem

<2> Wir fügen alle Rollen hinzu

<3> Und speichern den Nutzer und geben ihn zurück

== Initializierung der Datenbank

Die Initialisierung der Datenbank können wir jetzt in eine extra Klasse verschieben,
und die `data.sql` löschen.

Dazu legen wir eine neue Klasse `InitializeDatabase` an.
Diese ist eine `InitializingBean`, deren `afterPropertiesSet` beim Start der Anwendung ausgeführt wird.

[source, java]
.InitializeDatabase.java
----
include::../javasrc/9/src/main/java/tdpe/example/InitializeDatabase.java[tags=class]
----

<1> Zuerst versuchen wir, den Nutzer zu laden. Existiert dieser,
muss die Datenbank nicht weiter gefüllt werde

<2> Existiert er nicht, legen wir den Nutzer neu an

<3> Außerdem legen wir erneut die beiden Artikel an

[WARNING]
====
Die `data.sql` muss gelöscht werden!
====

== Speichern der Datenbank

Damit die Datenbank auch gespeichert wird, müssen wir einfach einen Pfad für diese angeben:

[source,properties]
.application.properties
----
include::../javasrc/1/src/main/resources/application.properties[]
----
<1> Als Pfad  nutzen wir einfach das Unterverzeichnis `data`, in diesem wird dann die Datenbank `blog` erstellt.
Der Pfad gibt dabei an, dass es eine `jdbc`-Datenbank vom Typ `h2` ist, die als Datei vorliegt

<2> Zusätzlich setzen wir noch die `ddl-auto`-Propertie auf `update`.
Dadurch wir die Datenbank beim starten de Anwendnung an das aktuelle Schema angepasst.
Normalerweise steht dies auf `create-drop`, damit würde die Anwendung be jedem Starten neu erstellt und beim Beenden gelöscht (`drop`) werden

== Starten

Wir können die Anwendung wieder starten.

Fügen wir Artikel hinzu, beenden die Anwedung und starten sie neu,
sind die alten Artikel immer noch vorhanden
