== Weitere Hinweise

=== Grundlage für eigenes Projekt

* In der pom.xml sollten groupId und artifactID des Projektes angepasst werden
** Dabei bietet sich z.B. `de.unibi.tdpe.ss2017.*team-nr*` als groupId an
* Die Ober-Packages (`tdpe.example`) sollten passend zu eurer groupId und artifactId angepasst werden

* Die ExampleApplication sollte einen sinnvolleren Namen für euer Programm bekommen

=== Build-Artefakte

Beim Build wird eine *.jar und eine *-exec.jar generiert.
Letztere kann zum direkten Ausführen (mit `java -jar`) der Applikation verwendet werden.


=== Autovervollständigung in templates

Für viele model-Attribute bietet IntelliJ IDEA innerhalb der Templates bereits Autovervollständigung.
Für alle anderen, z.B. Listen von Objekten, kann man angeben, welcher Typ es ist.
Für die View aus Schritt 4 sieht dies folgendermaßen aus:

[source,html]
----
<!--/*@thymesVar id="blogPosts" type="java.util.List&lt;de.unibielefeld.techfak.tdpe.thymeleaf.domain.BlogPost&gt;"*/-->
<tr th:each="post:${blogPosts}">
    ...
</tr>
----
IntelliJ IDEA "weiß" damit, das `blogPosts`
vom Typ `java.util.List<de.unibielefeld.techfak.tdpe.thymeleaf.domain.BlogPost>` ist,
und kann dann sowohl für die Liste, als auch für Objekte aus der Liste (hier `post`) Autovervollständigung bieten.


=== PUT, PATCH & DELETE in HTML

Die http-Methoden PUT,PATCH,DELETE lassen sich in normalem HTML nicht verwenden,
jedoch bietet Spring Boot Möglichkeiten, diese zusätzlich zu GET und POST zu nutzen.

Gibt man die `form`-Methode in Templates nicht mit `method`, sondern mit
`th:method` an, wandelt Spring die Methoden in für den Browser passende um, in der  Anwendung lassen sie sich aber als PUT,PATCH & DELETE verwenden.
