== Weitere Hinweise

=== Grundlage für eigenes Projekt

In eurem Team-Repo findet ihr bereits ein Initiales Projekt.

Wenn ihr möchtet, könnt ihr für dieses in der pom.xml den Namen und die Beschreibung anpassen.


=== Auto-Reload

Bei Änderungen an der Anwendung können diese automatisch neu geladen werden,
ohne das neu gestartet werden muss.

Dazu muss in IntelliJ die entsprechende Option aktiviert sein, damit Änderung direkt kompiliert werden:

Einstellungen -> Build, Execution, Deployment -> Compiler: "Build Project automatically"

Außerdem muss das Projekt über das Terminal gestartet sein, und nicht direkt über IntelliJ.


=== Build-Artefakte

Beim Build wird eine *.jar und eine *-exec.jar generiert.
Letztere kann zum direkten Ausführen (mit `java -jar`) der Applikation verwendet werden.

Diese steht auch im Jenkins zum Download bereit.

=== Autovervollständigung in templates

Für viele model-Attribute bietet IntelliJ IDEA innerhalb der Templates bereits Autovervollständigung.
Für alle anderen, z.B. Listen von Objekten, kann man angeben, welcher Typ es ist.
Für die View aus Schritt 4 sieht dies folgendermaßen aus:

[source,html]
----
<!--/*@thymesVar id="blogPosts" type="java.util.List&lt;de.unibielefeld.techfak.tdpe.thymeleaf.domain.BlogPost&gt;"*/-->
<tr th:each="post:${blogPosts}">
    ...
</tr>
----
IntelliJ IDEA "weiß" damit, das `blogPosts`
vom Typ `java.util.List<de.unibielefeld.techfak.tdpe.thymeleaf.domain.BlogPost>` ist,
und kann dann sowohl für die Liste, als auch für Objekte aus der Liste (hier `post`) Autovervollständigung bieten.


=== PUT, PATCH & DELETE in HTML

Die http-Methoden PUT,PATCH,DELETE lassen sich in normalem HTML nicht verwenden,
jedoch bietet Spring Boot Möglichkeiten, diese zusätzlich zu GET und POST zu nutzen.

Gibt man die `form`-Methode in Templates nicht mit `method`, sondern mit
`th:method` an, wandelt Spring die Methoden in für den Browser passende um, in der  Anwendung lassen sie sich aber als PUT,PATCH & DELETE verwenden.
