== Weitere Hinweise

=== Grundlage für eigenes Projekt

In eurem Team-Repo findet ihr bereits ein Initiales Projekt.

Für dieses solltet ihr in der pom.xml den Namen und die Beschreibung anpassen.


=== Auto-Reload

Bei Änderungen an der Anwendung können diese automatisch neu geladen werden,
ohne das neu gestartet werden muss.

Dazu muss in IntelliJ die entsprechende Option aktiviert sein, damit Änderung direkt kompiliert werden:

Einstellungen -> Build, Execution, Deployment -> Compiler: "Build Project automatically"

Außerdem muss das Projekt über das Terminal mit Maven gestartet werden, und nicht direkt über IntelliJ.


=== Autovervollständigung in templates

Für viele model-Attribute bietet IntelliJ IDEA innerhalb der Templates bereits Autovervollständigung.
Für alle anderen, z.B. Listen von Objekten, kann man angeben, welcher Typ es ist.
Für die View aus Schritt 4 sieht dies folgendermaßen aus:

[source,html]
----
<!--/*@thymesVar id="blogPosts" type="java.util.List<gpse.example.domain.BlogPost>;"*/-->
<tr th:each="post:${blogPosts}">
    ...
</tr>
----
IntelliJ IDEA "weiß" damit, das `blogPosts`
vom Typ `java.util.List<gpse.example.domain.BlogPost>` ist,
und kann dann sowohl für die Liste, als auch für Objekte aus der Liste (hier `post`) Autovervollständigung bieten.


=== PUT, PATCH & DELETE in HTML

Die http-Methoden PUT,PATCH,DELETE lassen sich in normalem HTML nicht verwenden,
jedoch bietet Spring Boot Möglichkeiten, diese zusätzlich zu GET und POST zu nutzen.

Gibt man die `form`-Methode in Templates nicht mit `method`, sondern mit
`th:method` an, wandelt Spring die Methoden in für den Browser passende um, in der  Anwendung lassen sie sich aber als PUT,PATCH & DELETE verwenden.


=== Anbieten einer REST-API in Spring

In diesem Tutorial liefern die Methoden im Controller Objekte vom Typ `ModelAndView` zurück, die mithilfe eines Templates als HTML Seite gerendert werden um sie ansehen zu können.

Ihr könnt aber auch sehr einfach einen Controller erstellen der über JSON-Objekte kommuniziert, indem ihr den entsprechenden Controller mit `@RestController` annotiert.

Dies kann zum Beispiel hilfreich sein, wenn ihr dynamisch per JavaScript auf Daten eurer Anwendung zugreifen möchtet.
